# Generated by Django 4.2.4 on 2023-09-19 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_remove_notification_user_notification_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at']},
        ),
    ]
